### ISSUE TITLE
byteLength should be Int

### ISSUE THREAD

**Issue by felixSchl** [jutaro/purescript-typedarray#7]
I think that intuitively at least, `byteLength` should be `Int`. What's the reason for it being `Number`?

**Comment by jutaro** [comment]
Hi Felix,
I beleive I choose Number here, because Int is restricted to a maximum 2147483647, and well in principle (and maybe in practice?) it can be possible to have bigger arrays.

**Comment by felixSchl** [comment]
Hm I see, thanks for the explanation, that makes sense in the context of JS
