### ISSUE TITLE
Search for co-maintainers

### ISSUE THREAD

**Issue by menelaos** [jutaro/purescript-typedarray#9]
The recent [commit](https://github.com/jutaro/purescript-typedarray/commit/85e997e95eee69e13c80a1ff35b4936bff419fe4) states:

> Sorry for the late merge. I'm moving away from using purescript and look for maintainers for my packages.

I would be willing to do the occasional version bump. However, I'm only really using one function out of this library, so I would not be actively working on it.

@garyb, @paf31: Would this library be a candidate for purescript-contrib?

Also pinging past contributors: @newlandsvalley @jacereda @mgmeier

**Comment by newlandsvalley** [comment]
I'm pretty much in the same boat, only I make no direct use of the library at all.  I submitted the 0.12 PR just because I needed b64.  I'd be willing to help on the same basis as you.

**Comment by mgmeier** [comment]
@newlandsvalley @menelaos  I've stepped in as the new maintainer of @jutaro 's purescript packages. Please contact me / open issues / submit PRs if there's anything you might need. Closing this issue for now.

**Comment by newlandsvalley** [comment]
Excellent!  Many thanks.

**Comment by menelaos** [comment]
Thanks for stepping in! Could you release a new version (i.e. push a new tag)?
